spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: springbatch
    password: springbatch
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: create-drop  # Changed from 'none' to 'create-drop'
    show-sql: true           # Optional: to see generated SQL
    properties:
      hibernate:
        format_sql: true     # Optional: to format SQL output
  batch:
    job:
      name: chequeJob
      enabled: true
    jdbc:
      initialize-schema: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
spring.docker.compose.enabled: false

logging:
  level:
    org.springframework.batch: DEBUG
    dz.eadn.readerpro: DEBUG
